llm:
  default_provider: openrouter
  models:
    player1:
      default: google/gemini-2.0-flash-001
      backup: google/gemini-2.0-flash-001
      max_tokens: 1000
      temperature: 0.7
    player2:
      default: google/gemini-2.0-flash-001
      backup: google/gemini-2.0-flash-001
      max_tokens: 1000
      temperature: 0.7
    player3:
      default: google/gemini-2.0-flash-001
      backup: google/gemini-2.0-flash-001
      max_tokens: 1000
      temperature: 0.7
    coordinator:
      default: google/gemini-2.0-flash-001
      backup: google/gemini-2.0-flash-001
      max_tokens: 1000
      temperature: 0.5

spaces:
  pvp_arena_v1:
    max_rounds: 5
    starting_coins: 10
    min_transfer: 1
    players:
      - Alpha
      - Beta
  merchants_1o1:
    max_rounds: 5
    starting_coins: 10
    min_transfer: 1
    players:
      - Marco Polo
      - Trader Joe
  merchants_multi:
    max_rounds: 5
    starting_coins: 10
    min_transfer: 1
    players:
      - Alex
      - Blake
      - Charlie

logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  directory: logs

network:
  proxy: null
  timeout: 30
  max_retries: 3
  retry_delay: 2

game:
  max_rounds: 5
  starting_coins: 10
  min_transfer: 1
  players:
    - Alex
    - Blake
    - Charlie