services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - ./credentials:/app/credentials:ro
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DEBUG=true
    env_file:
      - .env
    command: poetry run uvicorn src.api.server:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    command: pnpm dev

networks:
  default:
    driver: bridge 