version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./config.yaml:/app/config.yaml
    environment:
      - PYTHONPATH=/app
      - DEBUG=true
    env_file:
      - .env
    command: poetry run uvicorn src.api.server:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - game_network

networks:
  game_network:
    driver: bridge 