version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./config.yaml:/app/config.yaml
    environment:
      - PYTHONPATH=/app
      - DEBUG=true
    env_file:
      - .env
    command: poetry run uvicorn src.api.server:app --host 0.0.0.0 --port 8000 --reload

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
    depends_on:
      - api 