version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8000:8000"
    volumes:
      - ./credentials:/app/credentials:ro
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - DEBUG=false
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

networks:
  game_network:
    driver: overlay 